/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    colors: {
      // main: "#133E87",
      // "light-main": "#42659f",
      // secondary: "#608BC1",
      // "light-secondary": "#CBDCEB",
      // "light-secondary-200": "#98A0B4",
      // "light-secondary-300": "#BACAE4",
      // "danger-300": "#D93A40",
      // "danger-200": "#e16166",
      // white: "#FFFFFF",
      // background: "#F3F2F0",
      // yellow: "#EECC00",
      // "light-danger": "#FEEEEF",
      // offWhite: "#E4E5E8",
      // "gray-100": "#ccc",
      // "gray-200": "#D9D9D9",
      // "gray-300": "#999",
      // "gray-400": "#9BA1AA",
      // "gray-500": "#767F8C",
      // "gray-600": "#5E6670",
      // "gray-700": "#4F4F4F",
      // "gray-800": "#2D2D2D",
      // "green-100": "#0BA02C",
      // "green-200": "#017550",
      // "light-green": "#E7F6EA",
      // "main-dark": "#1B1F23",
      main: "rgba(var(--main), <alpha-value>)",
      "light-main": "rgba(var(--light-main), <alpha-value>)",
      secondary: "rgba(var(--secondary), <alpha-value>)",
      "light-secondary": "rgba(var(--light-secondary), <alpha-value>)",
      "light-secondary-200": "rgba(var(--light-secondary-200), <alpha-value>)",
      "light-secondary-300": "rgba(var(--light-secondary-300), <alpha-value>)",
      "danger-300": "rgba(var(--danger-300), <alpha-value>)",
      "danger-200": "rgba(var(--danger-200), <alpha-value>)",
      white: "rgba(var(--white), <alpha-value>)",
      background: "rgba(var(--background), <alpha-value>)",
      yellow: "rgba(var(--yellow), <alpha-value>)",
      "light-danger": "rgba(var(--light-danger), <alpha-value>)",
      offWhite: "rgba(var(--offWhite), <alpha-value>)",
      "gray-100": "rgba(var(--gray-100), <alpha-value>)",
      "gray-200": "rgba(var(--gray-200), <alpha-value>)",
      "gray-300": "rgba(var(--gray-300), <alpha-value>)",
      "gray-400": "rgba(var(--gray-400), <alpha-value>)",
      "gray-500": "rgba(var(--gray-500), <alpha-value>)",
      "gray-600": "rgba(var(--gray-600), <alpha-value>)",
      "gray-700": "rgba(var(--gray-700), <alpha-value>)",
      "gray-800": "rgba(var(--gray-800), <alpha-value>)",
      "green-100": "rgba(var(--green-100), <alpha-value>)",
      "green-200": "rgba(var(--green-200), <alpha-value>)",
      "light-green": "rgba(var(--light-green), <alpha-value>)",
      "main-dark": "rgba(var(--main-dark), <alpha-value>)",
    },
    extend: {
      animation: {
        slide: "slideX 35s linear infinite",
        fadeIn: "fadeIn 0.3s ease-out forwards",
        enterNotification: "enter 0.2s ease-out",
        leaveNotification: "leave 0.15s ease-in forwards",
      },
      keyframes: {
        slideX: {
          "0%": { transform: "translateX(-100%)" },
          "100%": { transform: "translateX(100%)" },
        },
        fadeIn: {
          "0%": { opacity: "0", transform: "scale(0.95)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        enter: {
          " 0%": { transform: "scale(0.9)", opacity: 0 },
          "100%": { transform: "scale(1)", opacity: 1 },
        },
        leave: {
          "0%": { transform: "scale(1)", opacity: 1 },
          "100%": { transform: "scale(0.9)", opacity: 0 },
        },
      },
    },
  },
  plugins: [],
};
